### ISSUE TITLE
Issues with storyboards

### ISSUE THREAD

**Issue by Alex293** [CosynPa/TZStackView#5]
Hi,

there is an issue with storyboards when designing views are not always we updated even without changes to the demo. Sometimes a change to any view make others invisible and changing again make them appear but it's really buggy.

Using Xcode 8 and branch swift 3 and 2.3 (I'm only interested by the 3 but same thing appear on 2.3)

I think it's a ib designable bug because code is perfectly working at run time.

Tho great lib, saved my day while porting my app to iOS 8

**Comment by CosynPa** [comment]
I think it's an Xcode bug. Sometimes the frame in the size inspector is correct, but the view in IB doesn't appear to be in the correct size.
