### ISSUE TITLE
Background colour

### ISSUE THREAD

**Issue by Alex293** [CosynPa/TZStackView#6]
Hi,

background colour seems to have no effect is this how it's supposed to be ?

**Comment by CosynPa** [comment]
Yes. From UIStackView reference:

> The UIStackView is a nonrendering subclass of UIView; that is, it does not provide any user interface of its own. Instead, it just manages the position and size of its arranged views. As a result, some properties (like backgroundColor) have no effect on the stack view. Similarly, you cannot override layerClass, drawRect:, or drawLayer:inContext:.
